version: '3.8'
services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=myuser
    ports:
      - '5432:5432'
    networks:
      - spring-app-network

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8082:8082'
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/mydatabase
      - SPRING_DATASOURCE_USERNAME=myuser
      - SPRING_DATASOURCE_PASSWORD=secret
    depends_on:
      - postgres
    networks:
      - spring-app-network

networks:
  spring-app-network:
    driver: bridge
